### ISSUE TITLE
mint start throws up on missing catches

### ISSUE THREAD

**Issue by HorizonShadow** [mint-lang/mint#60] opened 2018-07-16 23:21 UTC
Sorry for the bad title.

If you have a `do {}` expression, and you don't handle all possible errors, I'm getting the following:

```
josh@DESKTOP-D449P1P:/mnt/c/users/horiz/dev/snippets-frontend$ mint start
Mint - Running the development server
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
⚙ Ensuring dependencies... 3.129ms
Unhandled exception: Negative count: -97 (ArgumentError)
Failed to raise an exception: END_OF_STACK
[0x6c5b36] ???
[0x464373] __crystal_raise +195
[0x465198] ???
[0x4c17ca] ???
[0x4ba709] ???
[0x4b984e] ???
[0x46c53b] ???
[0x501da9] ???
[0x467e89] main +217
[0x7fe425340830] __libc_start_main +240
[0x419dc9] _start +41
```

`mint build` prints:

```
josh@DESKTOP-D449P1P:/mnt/c/users/horiz/dev/snippets-frontend$ mint build
Mint - Building for production
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
⚙ Ensuring dependencies... 81μs
⚙ Clearing the "dist" directory... 6.955ms
⚙ Compiling your appliction:
  ➔ Parsing 71 source files... 735.821ms
  ➔ Type checking:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

░ TYPE ERROR ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

I am checking if all the possible errors are handled in a do expression.

I found that these types are not handled:

  • Object.Error

Here is the relevant code snippet:

┌───┬ source/Snippet.Store.mint ───────────────────────────────────────────────┐
│137│         do {                                                             │
│138│             next { state | loading = true }                              │
│139│             response = endpoint() + Number.toString(id)                  │
│140│                 |> Http.get()                                            │
│141│                 |> Http.send()                                           │
│142│             object = response.body                                       │
│143│                 |> Json.parse()                                          │
│144│                 |> Maybe.toResult("Json Error")                          │
│145│                                                                          │
│146│             snippet = decode object as Snippet                           │
│147│             next { state | snippet = snippet }                           │
│148│         } catch Http.ErrorResponse => error {                            │
│149│             next { state | error = "Error" }                             │
│150│         } catch String => error {                                        │
│151│             next { state | error = error }                               │
│152│         }                                                                │
│153│     }                                                                    │
│154│                                                                          │
│155│     fun setPage(page : Number) : Void {                                  │
│156│         next { state | page = page }                                     │
│157│     }                                                                    │
│158│                                                                          │
│159│     fun setName(name:String):Void {                                      │
│160│         next { state | snippet = { snippet | name = name }}              │
│161│     }                                                                    │
│162│                                                                          │
│163│     fun setContent(content:String):Void {                                │
│164│         next { state | snippet = { snippet | content = content }}        │
└───┴──────────────────────────────────────────────────────────────────────────┘

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
There was an error exiting...
```

I'm not 100% sure if this is exactly what's causing it, but I can reproduce it every time by removing a case. If I add the missing case, everything works fine.

**Comment by gdotdesign** [comment] 2018-07-17 03:35
If you could provide a small reproducible example that would be really helpful.

Here are some questions to track down the problemn:
* does this happen also when the server is running? if so does it exit after the error? 
* I think you are on WLS, but what distribution (Ubuntu, Debian)?
* did you compile Mint from source or using the daily binary?

**Comment by HorizonShadow** [comment] 2018-07-17 09:43
While the server is running, I get 

```
Unhandled exception in spawn:
Negative count: -97 (ArgumentError)
```

I seems like it stops watching the source at this point, but it doesn't crash out. Just idles on that message.

* WSL Ubuntu
* Source

**Comment by gdotdesign** [comment] 2018-09-09 09:08
I'm closing this since I could not reproduce this, also there is a new release since then, if the error persists please open this issue again.

**Closed by gdotdesign** 2018-09-09 09:08 UTC
Labels: bug, needs example
