### ISSUE TITLE
Dependency external CSS is not being bundled correctly

### ISSUE THREAD

**Issue by farism** [mint-lang/mint#649] opened 2023-09-04 00:42 UTC
<img width="1216" alt="Screenshot 2023-09-02 at 3 40 23 AM" src="https://github.com/mint-lang/mint/assets/3803714/513f0ebe-bec4-42ec-9d9f-e673c54e35b1">

Given this scenario I would expect the resulting external css to be 

```css
body { 
  margin: 5px;
}

.package-a {
  padding: 10px;
}
```

But instead I am seeing

<img width="711" alt="Screenshot 2023-09-02 at 3 40 13 AM" src="https://github.com/mint-lang/mint/assets/3803714/39d45b11-f7a2-4a14-8e97-e6498317e8b1">

It looks like it duplicated the application external css instead of concatenating the application + package external css.

**Comment by gdotdesign** [comment] 2024-11-06 15:37
The ability to load external assets like the issue is for are no longer possible in `0.20.0` so I'm closing this.

**Closed by gdotdesign** 2024-11-06 15:37 UTC
