### ISSUE TITLE
`Missing hash key: "snippet"` error on invalid mint.json

### ISSUE THREAD

**Issue by bjansen** [mint-lang/mint#358] opened 2021-01-16 20:43 UTC
When `mint.json` is configured with an invalid (non-integer) value, `mint` crashes instead of showing the relevant snippet:
```json
  "formatter": {
    "indent-size": true
  }
```

```
mint compile
Unhandled exception: Missing hash key: "snippet" (KeyError)
  from raise<KeyError>:NoReturn
  from Hash(String, Array(Mint::TypeChecker::Record | Mint::TypeChecker::Type | Mint::TypeChecker::Variable) | Array(String) | Mint::Ast::Node | Mint::TypeChecker::Record | Mint::TypeChecker::Type | Mint::TypeChecker::Variable | String | Tuple(Mint::Ast::Node, Int32))+@Hash(K, V)#[]<String>:(Array(Mint::TypeChecker::Record+ | Mint::TypeChecker::Type | Mint::TypeChecker::Variable) | Array(String) | Mint::Ast::Node+ | Mint::TypeChecker::Record+ | Mint::TypeChecker::Type | Mint::TypeChecker::Variable | String | Tuple(Mint::Ast::Node+, Int32))
  from Mint::Messages::MintJsonIndentSizeInvalid#build:Array(Array(Mint::Message::Bold | Mint::Message::Code | Mint::Message::Text) | Mint::Message::Pre | Mint::Message::Snippet | Mint::Message::StringList | Mint::Message::Title | Mint::Message::Type | Mint::Message::TypeList)
  from Mint::Message+@Mint::Message#render<Mint::Render::Terminal>:IO+
  from Mint::Cli::Compile#parse_and_run:Nil
  from Mint::Cli#parse_and_run:Nil
  from __crystal_main
  from main
Mint - Compiling
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

**Comment by bjansen** [comment] 2021-01-16 20:45
Also, I think negative values (and perhaps even 0) should be forbidden as well.

**Comment by gdotdesign** [comment] 2021-04-12 15:48
Duplicate of https://github.com/mint-lang/mint/issues/376, fixed in master.

**Closed by gdotdesign** 2021-04-12 15:48 UTC
Labels: bug
