### ISSUE TITLE
Should tuple destructuring require all of it's items to be destructured?

### ISSUE THREAD

**Issue by Namek** [mint-lang/mint#234] opened 2020-03-27 01:11 UTC
## Issue
 tuple destructure matches different tuple size.

I have a function that returns type `traverse(...) : Tuple(Maybe(Number), Bool, Number)`, then I destructure its result:

```
 {idx2, distance} =
    traverse(genState, idx, direction, false)
```

It turned out the `distance` is `Bool` instead `Number`. In my opinion it shouldn't even compile since the function defined returning Tuple to have size 3 but the destructure tuple was size 2.

## SSCCE:

```
component Main {
  fun render : Html {
    <div>
      <{test()}>
    </div>
  }
  
  fun test() : String {
   try {
    /* this one should not compile */
    {a, b} =
       tuple3func()
       
    {a, b, c} =
      tuple3func()
  
     "if it compiles then there is a compiler bug"
    }
  }
  
  fun tuple3func() : Tuple(Maybe(Number), Bool, Number) {
    {Maybe::Nothing, true, 123}
  }
}
```

https://sandbox.mint-lang.com/sandboxes/pSUaWRPzwjxJJQ

**Comment by gdotdesign** [comment] 2020-03-27 05:13
I understand the issue, but I'm not sure that we should restrict it, I think there might be times when it makes sense to destructure only the first X elements of a tuple.

For example in Crystal it works this way https://play.crystal-lang.org/#/r/8s0i

**Comment by Namek** [comment] 2020-03-27 11:04
Crystal is not perfect then.

I would rather have this:

```
{a, b, _} = getTuple3()
```

**Comment by Sija** [comment] 2020-03-27 11:13
> Crystal is not perfect then.

Well, nothing **is**. It's OK to have a different PoV, but it's not cool to force it on others. Your example if no different functionally than the current state of things - it's just more explicit - which you can argue is better or worse - I like implicitness for example and I wouldn't like to be _forced_ to be explicit like this for no reason other than your whimsy.

**Comment by Namek** [comment] 2020-03-27 11:25
@Sija Sorry for making you feeling bad about this.

If this is not a bug but designed then you should close this @gdotdesign

**Comment by gdotdesign** [comment] 2020-03-27 11:32
@Namek It is good input. I don't want to have a language which people don't like working with.

It was designed this way because it gives people more flexibility, if the majority of the users don't like this we can change it later on, so I'll keep the issue and change the title to reflect that.

**Comment by Sija** [comment] 2020-03-27 12:00
@Namek Sorry for the harsh tone of my previous comment, just wanted to point out it's a discussible matter and IMO shouldn't be treated as a bug. AFAIK JS, PHP, Ruby & Crystal exhibit the same behaviour, Elixir & Python OTOH won't allow it - do you know any other language that would force explicitness on the user/dev?

**Comment by Namek** [comment] 2020-03-27 12:03
> @Namek Sorry for the harsh tone of my previous comment, just wanted to point out it's a discussible matter and IMO shouldn't be treated as a bug. AFAIK JS, PHP, Ruby & Crystal exhibit the same behaviour, Elixir & Python OTOH won't allow it - do you know any other language that would force explicitness on the user/dev?

Elm

**Comment by gdotdesign** [comment] 2020-03-27 12:10
Just wanted to mention that Elm only allows tuples the size of 2 or 3, we don't have that limitation.

**Comment by lukepighetti** [comment] 2020-05-05 16:51
I think the underscore argument omission doesn't feel right for Mint, we don't use it anywhere else. I think partial destructuring is quite "minty", if you will.

**Comment by Sija** [comment] 2020-12-21 19:18
Looks resolved, closing.

**Closed by Sija** 2020-12-21 19:18 UTC
Labels: discussion, needs decision
