### ISSUE TITLE
Mint start crashes on malformed mint.json

### ISSUE THREAD

**Issue by trapped** [mint-lang/mint#103] opened 2018-11-03 13:01 UTC
**Mint version**: Mint 0.3.1 Linux x86_64 (I think - although `mint version` prints 0.3.0)
**Issue**: Both `mint build` and `mint start` fail when reading a malformed `mint.json`:
```
Unhandled exception: Negative argument (ArgumentError)
Failed to raise an exception: END_OF_STACK
```
**Steps to reproduce**: simply add `//` (line comment) at the start of any line in `mint.json`; for example:
```
{
  //"name": "crash"
}
```
then run `mint start` or `mint build`; output:
```
Mint - Running the development server
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Unhandled exception: Negative argument (ArgumentError)
Failed to raise an exception: END_OF_STACK
[0x705b76] ???
[0x45c123] ???
[0x45cf78] ???
[0x4be938] ???
[0x4b7819] ???
[0x4b689d] ???
[0x46452b] ???
[0x501c83] ???
[0x45fbbd] ???
[0x8e5a7c] ???
[0x40ef5b] ???
```
or, for `mint build`:
```
Mint - Building for production
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Unhandled exception: Negative argument (ArgumentError)
Failed to raise an exception: END_OF_STACK
[0x705b76] ???
[0x45c123] ???
[0x45cf78] ???
[0x4be938] ???
[0x4b7819] ???
[0x4b689d] ???
[0x46452b] ???
[0x501c83] ???
[0x45fbbd] ???
[0x8e5a7c] ???
[0x40ef5b] ???
```

**Comment by DanielSokil** [comment] 2018-11-03 14:42
JSON does not support line comments, but we can return a friendlier error when json is invalid.

**Comment by trapped** [comment] 2018-11-03 16:52
Yes, that was an example of malformed JSON. How should the error be shown? In a text window like for build errors?

**Comment by gdotdesign** [comment] 2018-11-08 11:51
I could not reproduce this issue for some reason, I get this when try the given JSON:

```
Mint - Running the development server
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
⚙ Ensuring dependencies... 
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

░ MINT.JSON ERROR ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

I could not parse the following mint.json file: 

┌─┬ /home/gdot/Projects/mint-lang/mint-realworld/mint.json ────────────────────┐
│1│ {                                                                          │
│2│   //"name": "crash"                                                        │
│3│ }                                                                          │
└─┴────────────────────────────────────────────────────────────────────────────┘

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
There was an error exiting...
```
I'm on Linux as well.

@trapped could you try with this version [mint.zip](https://github.com/mint-lang/mint/files/2561454/mint.zip)? it will show a proper stack trace since it's not compiled using release mode.

@DanielSokil for me it errors out here https://github.com/mint-lang/mint/blob/master/src/mint_json.cr#L84 as it should.

**Comment by trapped** [comment] 2018-11-09 11:02
@gdotdesign I will try with your zipped release. Mind you that I was using 0.3.1 and not master so that might even fix it.

**Comment by trapped** [comment] 2018-11-11 14:29
@gdotdesign tried with the version you provided me; apart from an issue with missing `libevent-2.0.so.5` (solved by simply installing that version), I still get an `END_OF_STACK`instead of an error with the malformed `mint.json`:
```
Mint - Building for production
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Unhandled exception: Negative argument (ArgumentError)
Failed to raise an exception: END_OF_STACK
[0x79fce6] *CallStack::print_backtrace:Int32 +118
[0x73fd86] __crystal_raise +86
[0x7402ee] ???
[0x8be799] *Crystal::System::File::open<String, String, File::Permissions>:Int32 +201
[0x8b2abd] *File::new<String, String, File::Permissions, Nil, Nil>:File +45
[0x79740d] *CallStack::read_dwarf_sections:(Array(Tuple(UInt64, UInt64, String)) | Nil) +109
[0x79714d] *CallStack::decode_line_number<UInt64>:Tuple(String | Nil, Int32, Int32) +45
[0x7968f8] *CallStack#decode_backtrace:Array(String) +296
[0x7967b2] *CallStack#printable_backtrace:Array(String) +50
[0x7e017d] *Exception+ +77
[0x7dd096] *Exception+ +182
[0x995f28] *AtExitHandlers::run<Int32>:Int32 +488
[0xb634fb] *Crystal::main<Int32, Pointer(Pointer(UInt8))>:Int32 +139
[0x74aa16] main +6
[0x7f56bc040b97] __libc_start_main +231
[0x73a8d9] _start +41
[0x0] ???
```

**Comment by gdotdesign** [comment] 2019-05-27 14:59
I'm closing this since there were multiple releases since.

Feel free to open it if it comes up again.

**Closed by gdotdesign** 2019-05-27 14:59 UTC
Labels: question
