### ISSUE TITLE
Configuration web page doesn't work

### ISSUE THREAD

**Issue by muhyaz** [mint-lang/mint#620] opened 2023-07-13 13:34 UTC
The link for [Configuration](https://mint-lang.com/guide/getting-started/configuration) on the [LEARN](https://mint-lang.com/guide)  web page doesn't work. Just a white page is shown.

**Comment by Sija** [comment] 2023-07-13 14:20
Duplicate of https://github.com/mint-lang/mint-website-rails/issues/131

**Closed** 2023-07-13 14:20 UTC
